# Generated by Django 5.2.4 on 2025-07-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add a book'), ('can_change_book', 'can edit a book'), ('can_delete_book', 'can delete a book')]},
        ),
    ]
